# FlightTrails by Oribuin | Donate @ https://oribuin.xyz/donate

conditions:
  # Should flight trails activate when you use creative fly?
  creative-fly: true
  # Should flight trails activate when gliding with an elytra?
  elytra: true

# Which worlds should Flight Trails not activate in?
disabled-worlds:
  - 'disabled-world1'
  - 'disabled-world2'

particle-settings:
  # How many particles should spawn
  count: 2
  # How large should the particles be (Applies to REDSTONE Particles)
  size: 1.0

  # Set as 'LEGACY' for feet particles
  # Set as 'FANCY' for dual particles
  elytra-style: 'FANCY'
  # The default settings when a player's data is first generated.
  default:
    # Should flight trails be enabled by default?
    enabled: true
    # Default particle effect
    particle: 'REDSTONE'
    # Default particle block (Applies to: FALLING_DUST, BLOCK_CRACK, BLOCK_DUST)
    block: 'BLUE_CONCRETE'
    # Default particle item (Applies to: ITEM_CRACK)
    item: 'BLUE_CONCRETE'
    # Default particle color (Applies to: REDSTONE)
    color: 'BLACK'