#
# » FlightTrails by Oribuin «
#
# Add customizable flight trails

conditions:
  creative-fly: true
  elytra: true

disabled-worlds:
  - 'disabled-world1'
  - 'disabled-world2'

particle-settings:
  count: 2
  size: 1.0

# Do not change this number
file-version: '1.0.5'