# FlightTrails by Oribuin | Donate @ https://oribuin.xyz/donate
# Join https://oribuin.xyz/support if you are experiencing issues!

# Used for debugging SQL Stuff
debug: false

# Enable if you want to save everything in MySQL
mysql:
  table-prefix: flighttrails_
  enabled: false
  host: localhost
  port: 3306
  dbname: mysql
  username: Username
  password: Password
  ssl: true

# Lower if you are experiencing lag.
# Do not go lower than 1
particle-amount: 3
# This only applies to 'Redstone' Particles
particle-size: 1

# Default: 1
# Delay in ticks between each particle, Raise interval if the particles seem to cause lag.
# Do not go lower than 1
spawn-interval: 1

# Worlds trails will not spawn in.
disabled-worlds:
  - 'Disabled-World-1'
  - 'Disabled-World-2'

# Highly recommend keeping these particles disabled.
disabled-particles:
  - 'FLASH'
  - 'MOB_APPEARANCE'
  - 'BLOCK_MARKER'

# Should there be particles for elytras
elytra-particles: true
# DEFAULT = Particles look like they are coming out of the wings
# LEGACY = Spawns particles at feet instead
elytra-particle-style: DEFAULT

# Should Trails spawn if you are flying?
creative-fly-particles: true

# If the player has the invisibility potion effect, disable particles
hide-if-invisible: true