#
# » FlightTrails by Oribuin «
#
# Add customizable flight trails

conditions:
  creative-fly: true
  elytra: true

disabled-worlds:
  - 'disabled-world1'
  - 'disabled-world2'


particle-settings:
  count: 2
  size: 1.0
  # Set as 'LEGACY' for feet particles
  # Set as 'FANCY' for dual particles
  elytra-style: 'FANCY'
  # The default settings when a player's data is first generated.
  default:
    enabled: true
    particle: 'REDSTONE'
    block: 'BLUE_CONCRETE'
    item: 'BLUE_CONCRETE'
    color: 'BLACK'