name: FlightTrails
main: xyz.oribuin.flighttrails.FlightTrails
version: '1.0'
authors: [ Oribuin ]
api-version: '1.13'
description: Fly with style with unique particles!
softdepend: [ PlaceholderAPI ]