name: FlightTrails
main: xyz.oribuin.flighttrails.FlightTrails
version: '2.0.8'
authors: [ Oribuin ]
api-version: '1.13'
description: Fly with style with unique particles!
softdepend: [ PlaceholderAPI, WorldGuard ]