name: FlightTrails
main: xyz.oribuin.flighttrails.FlightTrails
version: @version@
author: Oribuin
api-version: "1.13"
description: A light weight flight particle color trail plugin | EULA Friendly | Perfect for ranks.
website: http://oribuin.xyz/
softdepend:
  - PlaceholderAPI
commands:
  trails:
    description: Main command
    usage: /trails