name: FlightTrails
main: xyz.oribuin.flighttrails.FlightTrails
version: '@version@'
authors: [Oribuin, Esophose]
api-version: '1.13'
description: Customize your flying with EULA friendly Flight Trails
website: https://oribuin.xyz/
softdepend: [PlaceholderAPI]
commands:
  trails:
    description: Main FlightTrails command
    usage: /trails [set/reload/toggle] [particle/item/block/color] [value] [player]

permissions:
  flighttrails.*:
    description: All permissions
    default: op
    children:
      - flighttrails.use
      - flighttrails.toggle
      - flighttrails.reload
      - flighttrails.set
      - flighttrails.set.particle
      - flighttrails.set.block
      - flighttrails.set.item
      - flighttrails.set.color
  flighttrails.set.*:
    description: All set command permissions
    default: op
    children:
      - flighttrails.set
      - flighttrails.set.particle
      - flighttrails.set.block
      - flighttrails.set.item
      - flighttrails.set.color
