name: FlightTrails
main: xyz.oribuin.flighttrails.FlightTrails
version: '@version@'
authors: [ Oribuin, Esophose ]
api-version: '1.16'
description: Customize your flying with EULA friendly Flight Trails
website: https://oribuin.xyz/
softdepend: [ PlaceholderAPI ]
commands:
  trails:
    description: Main FlightTrails command
    usage: /trails
    aliases: [ 'flighttrails' ]

permissions:
  flighttrails.*:
    description: All permissions
    default: op
    children:
      - flighttrails.use
      - flighttrails.toggle
      - flighttrails.reload
      - flighttrails.admin
      - flighttrails.set.*
      - flighttrails.particle.*
      - flighttrails.color.*

  flighttrails.set.*:
    description: All set command permissions
    default: op
    children:
      - flighttrails.set
      - flighttrails.set.particle
      - flighttrails.set.block
      - flighttrails.set.item
      - flighttrails.set.color

  flighttrails.color.*:
    description: All trail color permissions
    default: op
    children:
      - flighttrails.color.red
      - flighttrails.color.orange
      - flighttrails.color.yellow
      - flighttrails.color.lime
      - flighttrails.color.green
      - flighttrails.color.light_blue
      - flighttrails.color.cyan
      - flighttrails.color.blue
      - flighttrails.color.purple
      - flighttrails.color.pink
      - flighttrails.color.white
      - flighttrails.color.light_gray
      - flighttrails.color.black
      - flighttrails.color.custom

  flighttrails.particle.*:
    description: All trail particle permissions
    default: op
    children:
      - flighttrails.particle.explosion_normal
      - flighttrails.particle.explosion_large
      - flighttrails.particle.explosion_huge
      - flighttrails.particle.fireworks_spark
      - flighttrails.particle.water_bubble
      - flighttrails.particle.water_splash
      - flighttrails.particle.water_wake
      - flighttrails.particle.suspended
      - flighttrails.particle.suspended_depth
      - flighttrails.particle.crit
      - flighttrails.particle.crit_magic
      - flighttrails.particle.smoke_normal
      - flighttrails.particle.smoke_large
      - flighttrails.particle.spell
      - flighttrails.particle.spell_instant
      - flighttrails.particle.spell_mob
      - flighttrails.particle.spell_mob_ambient
      - flighttrails.particle.spell_witch
      - flighttrails.particle.drip_water
      - flighttrails.particle.drip_lava
      - flighttrails.particle.villager_angry
      - flighttrails.particle.villager_happy
      - flighttrails.particle.town_aura
      - flighttrails.particle.note
      - flighttrails.particle.portal
      - flighttrails.particle.enchantment_table
      - flighttrails.particle.flame
      - flighttrails.particle.lava
      - flighttrails.particle.cloud
      - flighttrails.particle.redstone
      - flighttrails.particle.snowball
      - flighttrails.particle.snow_shovel
      - flighttrails.particle.slime
      - flighttrails.particle.heart
      - flighttrails.particle.barrier
      - flighttrails.particle.item_crack
      - flighttrails.particle.block_crack
      - flighttrails.particle.block_dust
      - flighttrails.particle.water_drop
      - flighttrails.particle.mob_appearance
      - flighttrails.particle.dragon_breath
      - flighttrails.particle.end_rod
      - flighttrails.particle.damage_indicator
      - flighttrails.particle.sweep_attack
      - flighttrails.particle.falling_dust
      - flighttrails.particle.totem
      - flighttrails.particle.spit
      - flighttrails.particle.squid_ink
      - flighttrails.particle.bubble_pop
      - flighttrails.particle.current_down
      - flighttrails.particle.bubble_column_up
      - flighttrails.particle.nautilus
      - flighttrails.particle.dolphin
      - flighttrails.particle.sneeze
      - flighttrails.particle.campfire_cosy_smoke
      - flighttrails.particle.campfire_signal_smoke
      - flighttrails.particle.composter
      - flighttrails.particle.flash
      - flighttrails.particle.falling_lava
      - flighttrails.particle.landing_lava
      - flighttrails.particle.falling_water
      - flighttrails.particle.dripping_honey
      - flighttrails.particle.falling_honey
      - flighttrails.particle.landing_honey
      - flighttrails.particle.falling_nectar
      - flighttrails.particle.soul_fire_flame
      - flighttrails.particle.ash
      - flighttrails.particle.crimson_spore
      - flighttrails.particle.warped_spore
      - flighttrails.particle.soul
      - flighttrails.particle.dripping_obsidian_tear
      - flighttrails.particle.falling_obsidian_tear
      - flighttrails.particle.landing_obsidian_tear
      - flighttrails.particle.reverse_portal
      - flighttrails.particle.white_ash
      - flighttrails.particle.legacy_block_crack
      - flighttrails.particle.legacy_block_dust
      - flighttrails.particle.legacy_falling_dust
